# render.yaml for Uptime Kuma (Free Tier - Ephemeral Data)

services:
  - name: uptime-kuma # Service name
    type: web         # Service type: web for HTTP/HTTPS servers
    plan: free        # Render plan (free tier)
    env: docker       # Environment type: Deploying a Docker image
    image:
      url: louislam/uptime-kuma:1 # Docker image URL and tag
    ports:
      - port: 3001        # Internal port Uptime Kuma listens on
        protocol: TCP     # Protocol (TCP for HTTP)
    healthCheck:
      path: /             # Health check endpoint path
      initialDelaySeconds: 30 # Delay before first health check (seconds)
    # --- Persistent Disk (Optional - Requires Paid Plan) ---
    # Uncomment the 'disks' section below if you switch to a paid plan ('starter' or higher)
    # and need data persistence (e.g., monitor history, settings) across restarts/deploys.
    # The 'free' plan uses ephemeral storage (data is lost on restart/deploy).
    # disks:
    #   - name: uptime-kuma-data # Name for the persistent disk
    #     mountPath: /app/data     # Mount point inside the container (Uptime Kuma's data dir)
    #     sizeGB: 1                # Disk size (1 GB minimum for paid disks)




