# render.yaml for Uptime Kuma (Free Tier - Ephemeral Data)

services:          # Top-level key defining the list of services
  - name: uptime-kuma  # Start of the first service definition (list item)
    # --- Properties of the 'uptime-kuma' service ---
    type: web          # Service type (required)
    plan: free         # Instance plan (optional, defaults might apply)
    env: docker        # Deployment environment (required for Docker images)

    image:             # Image details (required for docker env)
      url: louislam/uptime-kuma:1 # Specific image URL and tag

    ports:             # Port mapping configuration for 'web' type
      - port: 3001     # The internal container port Uptime Kuma listens on
        protocol: TCP  # Protocol Render should expect (usually TCP for web)

    healthCheck:       # Health check configuration
      path: /          # Path Render should request to check health
      initialDelaySeconds: 30 # Wait time before first health check

    # --- Optional Persistent Disk (Commented Out) ---
    # Keep this commented if using the 'free' plan as disks are not free.
    # Uncomment and ensure 'plan' is 'starter' or higher if persistence is needed.
    # disks:
    #  - name: uptime-kuma-data
    #    mountPath: /app/data  # Default data directory for Uptime Kuma image
    #    sizeGB: 1             # Smallest paid disk size is 1 GB
